[package]
name = "rad-sync"
version = "0.1.0"
authors = ["The Radicle Team <dev@radicle.xyz>"]
edition = "2018"
license = "GPL-3.0-or-later"
description = "Synchronize radicle projects with seeds"

[dependencies]
anyhow = "1.0"
lexopt = { version = "0.2" }
librad = "0"
radicle-common = { path = "../common" }
radicle-terminal = { path = "../terminal" }
url = { version = "*" }
